name="ibp-cloudflare"
type="javascript"
compatibility_date = "2022-05-29"
account_id="e7ba07fb5b7b19ad68a4607943793353"
zone_id="2b00a637e3e451adb22f42e2afc84251"
routes = [
  "*internationalbudget.org/letter-from-our-executive-director-on-the-conflict-in-ukraine",
  "*internationalbudget.org/annualreport2021",
  "*internationalbudget.org/open-budget-survey*",
  "*internationalbudget.org/sites/default*",
  "*internationalbudget.org/themes*",
  "*internationalbudget.org/modules*",
  "*internationalbudget.org/libraries*",
  "*internationalbudget.org/views*",
  "*internationalbudget.org/core*",
  "*internationalbudget.org/ar/open-budget-survey/country-results*",
  "*internationalbudget.org/es/open-budget-survey/country-results*",
  "*internationalbudget.org/fr/open-budget-survey/country-results*",
  "*internationalbudget.org/hu/open-budget-survey/country-results*",
  "*internationalbudget.org/hy/open-budget-survey/country-results*",
  "*internationalbudget.org/id/open-budget-survey/country-results*",
  "*internationalbudget.org/ka/open-budget-survey/country-results*",
  "*internationalbudget.org/kk/open-budget-survey/country-results*",
  "*internationalbudget.org/mk/open-budget-survey/country-results*",
  "*internationalbudget.org/mn/open-budget-survey/country-results*",
  "*internationalbudget.org/ne/open-budget-survey/country-results*",
  "*internationalbudget.org/ps/open-budget-survey/country-results*",
  "*internationalbudget.org/ro/open-budget-survey/country-results*",
  "*internationalbudget.org/ru/open-budget-survey/country-results*",
  "*internationalbudget.org/sl/open-budget-survey/country-results*",
  "*internationalbudget.org/uk/open-budget-survey/country-results*",
  "*internationalbudget.org/prs/open-budget-survey/country-results*",
  "*internationalbudget.org/pt-pt/open-budget-survey/country-results*",
]
[vars]
ENVIRONMENT = "production"
REALM = "Pre-launch"
USER = "User"
PWD = "obs@2021"

[env.dev]
routes = [
  "*internationalbudget.org/letter-from-our-executive-director-on-the-conflict-in-ukraine",
  "*internationalbudget.org/open-budget-survey*",
  "*internationalbudget.org/annualreport2021",
  "*internationalbudget.org/sites/default*",
  "*internationalbudget.org/themes*",
  "*internationalbudget.org/modules*",
  "*internationalbudget.org/libraries*",
  "*internationalbudget.org/views*",
  "*internationalbudget.org/core*",
  "*internationalbudget.org/fr/open-budget-survey/country-results*",
  "*internationalbudget.org/es/open-budget-survey/country-results*",
  "*internationalbudget.org/pt-pt/open-budget-survey/country-results*",
  "*internationalbudget.org/ru/open-budget-survey/country-results*",
  "*internationalbudget.org/ar/open-budget-survey/country-results*",
  "*internationalbudget.org/ro/open-budget-survey/country-results*",
  "*internationalbudget.org/kk/open-budget-survey/country-results*",
  "*internationalbudget.org/prs/open-budget-survey/country-results*",
  "*internationalbudget.org/ps/open-budget-survey/country-results*",
  "*internationalbudget.org/sl/open-budget-survey/country-results*",
  "*internationalbudget.org/mn/open-budget-survey/country-results*",
  "*internationalbudget.org/ne/open-budget-survey/country-results*",
  "*internationalbudget.org/ka/open-budget-survey/country-results*",
  "*internationalbudget.org/id/open-budget-survey/country-results*",
  "*internationalbudget.org/mk/open-budget-survey/country-results*",
  "*internationalbudget.org/hy/open-budget-survey/country-results*",
  "*internationalbudget.org/uk/open-budget-survey/country-results*",
]

[env.dev.vars]
ENVIRONMENT = "development"
REALM = "Pre-launch"
USER = "User"
PWD = "obs@2021"
